### ISSUE TITLE
ASR.py not found 

### ISSUE THREAD

**Issue by saifbm** [ericwang915/AIML-CHATBOT#1]
I get an error when i execute main.py in line code `from ASR import record` because ASR.py file not found in the project, Is there someone has an idea about this please ?

**Comment by ericwang915** [comment]
ASR is a third party speech recognition python package which is not allowed to be open-sourced. Please comment the ASR related codes and use keyboard input for the testing purpose.

**Comment by saifbm** [comment]
ok thanks, it works well :+1:
